server:
  port: 9527
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/wty?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: ${db_password}
          driver-class-name: com.mysql.jdbc.Driver
        student:
          url: jdbc:mysql://localhost:3306/student?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: ${db_password}
          driver-class-name: com.mysql.jdbc.Driver
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
    
  jta:
    atomikos:
      properties:
        log-base-dir: ../logs
    transaction-manager-id: txManager 
#mybatis-plus:
 # mapper-locations: classpath*:mapper/**/*Mapper.xml
